### ISSUE TITLE
Chips

### ISSUE THREAD

**Issue by jozphlp** [OpenDEM/FastAI4DEM#1]
Hi, thanks for providing this notebooks. it's really useful. I am playing with it and I would like to expand it to other locations to see how it performs. Could you please share the code you used to break the DEM into smaller tiles? Thanks very much

**Comment by OpenDEM** [comment]
Hi, I added a simple script for local processing with GDAL: https://github.com/OpenDEM/FastAI4DEM/blob/main/create_subset_4sr.py
